### ISSUE TITLE
"Favorites.sqlite" is no longer the favorites file

### ISSUE THREAD

**Issue by Minami-tori-shima** [ramiroaraujo/alfred-transmit-workflow#1] opened 2013-12-22 02:58 UTC
On my system, your workflow doesn't work. It returns old favorites from Nov. 12th, because the file "Favorites.sqlite" hasn't been updated since Nov. 12th. Only the file "Favorites.xml" is up-to-date. Looking at the change log of Transmit, Nov. 12th coincides with the release of version 4.4.5. This leads me to think that version 4.4.5 of Transmit no longer uses SQL, which unfortunately renders your workflow useless.

**Comment by ramiroaraujo** [comment] 2014-01-24 12:11
Added support for both sqlite and xml, not closing since I'm not sure it's correctly working on all versions yet :)

**Comment by ramiroaraujo** [comment] 2014-01-30 17:41
btw, I can confirm it's working with both sqlite and xml
still, I'm re-building the workflow with different xml parser because of #2

**Closed as completed** 2014-01-30 17:41 UTC
